SELECT * FROM GLINKSREL WHERE MASTERTABLE LIKE 'TC%'

SELECT * FROM TCCOTACAO
SELECT * FROM TCCOTACAOITMMOV
SELECT * FROM TCORCAMENTO
SELECT * FROM TCITMORCAMENTO --PARA CADA FORNECEDOR A QTD DE ITENS

SELECT * FROM TCHISTCOTACAO
SELECT * FROM TCITMORCAMENTOGRP
SELECT * FROM TCITMORCGERADO
