Para executar uma formula dentro de uma consulta sql faça: :FRM_CodigoDaFormula ,exemplo:

SELECT 
:FRM_TOTVS.12  *  0.05 
FROM FLAN  
	JOIN SLAN  ON FLAN.IDLAN   = SLAN.IDLAN
              AND FLAN.CODCOLIGADA = SLAN.CODCOLIGADA
    JOIN SPARCELA ON SLAN.CODCOLIGADA = SPARCELA.CODCOLIGADA
                 AND SLAN.IDPARCELA  = SPARCELA.IDPARCELA
 WHERE SPARCELA.CODSERVICO = 4 
   AND FLAN.VALORBAIXADO IS  NOT NULL
   AND SUBSTRING(FLAN.HISTORICO, 1, 10) =  :FRM_TOTVS.13
   AND FLAN.PERLETIVO = :FRM_TOTVS.14