------- Generated by SYS.DBMS_METADATA on 28-jan-2010 at 14:22:41 -------

  CREATE OR REPLACE PROCEDURE "RM"."GERA_TOKEN2" IS
-- Purpose: Prencher a table de token baseado nos tokens do campo nome da tabela ppesoa

-- Declare program variables as shown above
   CURSOR CPESSOA IS 
      SELECT DISTINCT NOME FROM PPESSOA WHERE CPF IS NULL AND CARTIDENTIDADE IS NULL;
   TOK PPESSOA.NOME%TYPE;
   TOK2 PPESSOA.NOME%TYPE;
   STR PPESSOA.NOME%TYPE;
   I INTEGER;
   J INTEGER;     
   TAM INTEGER;
   QTD INTEGER;
   IDD TOKEN.ID%TYPE;

BEGIN
   DELETE FROM TOKEN;
   COMMIT;

   FOR X IN CPESSOA LOOP
      STR := REGEXP_REPLACE(X.NOME,'( ){2,}',' ');
      TAM := COUNT_TOKEN(STR);
      IF(TAM>1) THEN
         FOR I IN 1..TAM-1 LOOP
            TOK := GET_TOKEN(STR,I);
            TOK := TRANSLATE(TRIM(UPPER(TOK)),'ÁÃÂÀÉÊÈÍÌÓÒÔÕÚÙÛ','AAAAEEEIIOOOOUUU');

            IF(LENGTH(TOK)>3) THEN
               FOR J IN I+1..TAM LOOP
                  TOK2 := GET_TOKEN(STR,J);
                  TOK2 := TRANSLATE(TRIM(UPPER(TOK2)),'ÁÃÂÀÉÊÈÍÌÓÒÔÕÚÙÛ','AAAAEEEIIOOOOUUU');
                  IF(LENGTH(TOK2)>3 AND TOK<>TOK2) THEN
                     BEGIN
                        SELECT NVL(MAX(ID),0)+1 INTO IDD FROM TOKEN;
                        INSERT INTO TOKEN(ID,NOME,QTD) VALUES(IDD,TOK||' '||TOK2,1);
                     EXCEPTION
                        WHEN DUP_VAL_ON_INDEX THEN NULL;
                           SELECT ID, QTD INTO IDD, QTD FROM TOKEN WHERE NOME = TOK||' '||TOK2;
                           UPDATE TOKEN SET TOKEN.QTD = QTD+1 WHERE ID = IDD;
                     END;     
                  END IF;     
               END LOOP; -- J
            END IF;
         END LOOP;  -- I 
               COMMIT;
      END IF;

   END LOOP;

   DBMS_OUTPUT.Put_Line('PROCEDIMENTO GERA TOKEN FINALIZADO COM SUCESSO!');  

EXCEPTION
    WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE(' ');
      DBMS_OUTPUT.PUT_LINE(SQLERRM);
 
END; -- Procedure 
 
 
/
