Rem  Copyright (c) 1996 by Oracle Corporation. All rights reserved. 
Rem    NAME
Rem      inst.sql
Rem    DESCRIPTION
Rem      
Rem    RETURNS
Rem 
Rem    NOTES
Rem      
Rem    MODIFIED   (MM\DD\YY)
Rem     mfreedma      09\11\96 -  Added Banner 

@%ows21%\sample\owa\dinst
@%ows21%\sample\owa\simple
@%ows21%\sample\owa\tables
@%ows21%\sample\owa\cookies
@%ows21%\sample\owa\iowaext
@%ows21%\sample\owa\ioptlock
