INSERT INTO temp_table (num_col, char_col)
  VALUES (1, 'hello')
/
INSERT INTO temp_table (num_col, char_col)
  VALUES (2, 'hello')
/
INSERT INTO temp_table (num_col, char_col)
  VALUES (3, 'hello')
/
INSERT INTO temp_table (num_col, char_col)
  VALUES (4, 'hello')
/
INSERT INTO temp_table (num_col, char_col)
  VALUES (5, 'hello')
/
INSERT INTO temp_table (num_col, char_col)
  VALUES (6, 'hello')
/
INSERT INTO temp_table (num_col, char_col)
  VALUES (7, 'hello')
/
