#--Netscape Communications Corporation MIME Information
# Do not delete the above line. It is used to identify the file type.

type=application/octet-stream  exts=bin
type=application/oda           exts=oda
type=application/pdf           exts=pdf
type=application/postscript    exts=ai,eps,ps
type=application/rtf           exts=rtf
type=application/x-mif         exts=mif
type=application/x-csh         exts=csh
type=application/x-dvi         exts=dvi
type=application/x-hdf         exts=hdf
type=application/x-latex       exts=latex
type=application/x-netcdf      exts=nc,cdf
type=application/x-sh          exts=sh
type=application/x-tcl         exts=tcl
type=application/x-tex         exts=tex
type=application/x-texinfo     exts=texinfo,texi
type=application/x-troff       exts=t,tr,roff
type=application/x-troff-man   exts=man
type=application/x-troff-me    exts=me
type=application/x-troff-ms    exts=ms
type=application/x-wais-source exts=src
type=application/zip           exts=zip
type=application/x-gtar        exts=gtar
type=application/x-shar        exts=shar
type=application/x-tar         exts=tar
type=application/mac-binhex40  exts=hqx

type=audio/basic               exts=au,snd
type=audio/x-aiff              exts=aif,aiff,aifc
type=audio/x-wav               exts=wav

type=image/gif                 exts=gif
type=image/ief                 exts=ief
type=image/jpeg                exts=jpeg,jpg,jpe
type=image/tiff                exts=tiff,tif
type=image/x-cmu-raster        exts=ras
type=image/x-portable-anymap   exts=pnm
type=image/x-portable-bitmap   exts=pbm
type=image/x-portable-graymap  exts=pgm
type=image/x-portable-pixmap   exts=ppm
type=image/x-rgb               exts=rgb
type=image/x-xbitmap           exts=xbm
type=image/x-xpixmap           exts=xpm
type=image/x-xwindowdump       exts=xwd

type=text/html                 exts=htm,html
type=text/plain                exts=txt,c,sql,java
type=text/richtext             exts=rtx
type=text/tab-separated-values exts=tsv
type=text/x-setext             exts=etx

type=video/mpeg                exts=mpeg,mpg,mpe
type=video/quicktime           exts=qt,mov
type=video/x-msvideo           exts=avi
type=video/x-sgi-movie         exts=movie

enc=x-gzip exts=gz
enc=x-compress exts=z
enc=x-uuencode exts=uu,uue

type=magnus-internal/imagemap  exts=map
type=magnus-internal/parsed-html exts=shtml
type=magnus-internal/cgi exts=cgi,exe,bat
