CREATE OR REPLACE FUNCTION MUDAPESSOA
  ( INCODIGO IN PPESSOA.codigo%TYPE, INNOME IN PPESSOA.NOME%TYPE) RETURN  VARCHAR2
  IS
     CURSOR C1 IS SELECT codigo, nome FROM PPESSOA A
     WHERE NOME IN
        (
           SELECT B.nome FROM PPESSOA B GROUP BY B.NOME HAVING COUNT(*) > 1
        )
        AND (
           exists (SELECT 0 FROM AUSOPROV B WHERE B.codpessoa = A.CODIGO)
               OR  exists (SELECT 0 FROM AVISITA B WHERE B.codpessoa = A.CODIGO)
   	  		   OR  exists (SELECT 0 FROM BEXECPROVA B WHERE B.codpessoa = A.CODIGO)
	 		   OR  exists (SELECT 0 FROM BEXECPROVA B WHERE B.codavaliado = A.CODIGO)
	 		   OR  exists (SELECT 0 FROM BHISTORICO B WHERE B.codpessoa = A.CODIGO)
	 		   OR  exists (SELECT 0 FROM BHISTORICO B WHERE B.codavaliado = A.CODIGO)
	 		   OR  exists (SELECT 0 FROM EALUNOS B WHERE B.codpessoa = A.CODIGO)
	 		   OR  exists (SELECT 0 FROM EALUNOS B WHERE B.pai = A.CODIGO)
	 		   OR  exists (SELECT 0 FROM EALUNOS B WHERE B.mae = A.CODIGO)
	 		   OR  exists (SELECT 0 FROM EALUNOS B WHERE B.respacad = A.CODIGO)
 	 		   OR  exists (SELECT 0 FROM EATENDIMENTO B WHERE B.codpessoa = A.CODIGO)
 	 		   OR  exists (SELECT 0 FROM EPROFES B WHERE B.codpessoa = A.CODIGO)
 	 		   OR  exists (SELECT 0 FROM HATENDENTE B WHERE B.codpessoa = A.CODIGO)
 			   OR  exists (SELECT 0 FROM HATENDIMENTOESP B WHERE B.codpessoa = A.CODIGO)
 			   OR  exists (SELECT 0 FROM KMAOOBRA B WHERE B.codpessoa = A.CODIGO)
 			   OR  exists (SELECT 0 FROM KREGISTROPRODUCAOQUALIDADE B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM LUSUARIO B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM MISMAPROP B WHERE B.codpessoaresp = A.CODIGO)
			   OR  exists (SELECT 0 FROM MISMAPROP B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM MMAOOBRAPDO B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM MMEDPALM B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM OFDESEMPENHOMENSAL B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM OFMAOOBRA B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM OFOBJINSTAL B WHERE B.idvendedor = A.CODIGO)
			   OR  exists (SELECT 0 FROM OFOBJINSTAL B WHERE B.idtecnico = A.CODIGO)
			   OR  exists (SELECT 0 FROM PANOTAC B WHERE B.codpessoaaut = A.CODIGO)
			   OR  exists (SELECT 0 FROM PANOTAC B WHERE B.codpessoa = A.CODIGO)
		 	   OR  exists (SELECT 0 FROM PENDPESSOA B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM PEXTERNO B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM PFHSTEND B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM PFUNC B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM PPESSOAPT B WHERE B.codigo = A.CODIGO)
			   OR  exists (SELECT 0 FROM SALUNO B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM SALUNO B WHERE B.codpessoaraca = A.CODIGO)
			   OR  exists (SELECT 0 FROM SCOORDENADOR B WHERE B.codpessoavice = A.CODIGO)
			   OR  exists (SELECT 0 FROM SCOORDENADOR B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM SDIRECAOFILIAL B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM SDIRECAOFILIAL B WHERE B.codpessoasec1 = A.CODIGO)
		 	   OR  exists (SELECT 0 FROM SDIRECAOFILIAL B WHERE B.codpessoasec2 = A.CODIGO)
			   OR  exists (SELECT 0 FROM SDIRETORDPTO B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM SDIRETORESCOLA B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM SPESSOA B WHERE B.codpessoapai = A.CODIGO)
			   OR  exists (SELECT 0 FROM SPESSOA B WHERE B.codpessoamae = A.CODIGO)
			   OR  exists (SELECT 0 FROM SPESSOA B WHERE B.codigo = A.CODIGO)
			   OR  exists (SELECT 0 FROM SPROFESSOR B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM SPSINSCRICAOAREAOFERTADA B WHERE B.codpessoaresponsavel = A.CODIGO)
			   OR  exists (SELECT 0 FROM TVEN B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VACOESVINCULADAS B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VADACAOAVALIADA B WHERE B.codavaliado = A.CODIGO)
			   OR  exists (SELECT 0 FROM VADVERTENCIA B WHERE B.codtestemun2 = A.CODIGO)
			   OR  exists (SELECT 0 FROM VADVERTENCIA B WHERE B.codtestemun1 = A.CODIGO)
			   OR  exists (SELECT 0 FROM VADVOGADO B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VAGENDAEXAM B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VAUSENCIA B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VAVALIADOAD B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VAVALIADORAD B WHERE B.codavaliador = A.CODIGO)
			   OR  exists (SELECT 0 FROM VBIBRIGADISTA B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VCANDIDATOS B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VCANDIDATOSCIPA B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VCOMPETENCIAPESSOA B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VCOMPETENCIAPESSOA B WHERE B.codcompetencia = A.CODIGO)
			   OR  exists (SELECT 0 FROM VCOMPETENCIAPESSOAHIST B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VCONSULTASPRONT B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VCTRLVACINAL B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VDESPESASREQSEL B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VEMPRESTIMOEPI B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VENVOLVIDOSCAT B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VEXPPROF B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VFUNCAOPRETENDIDA B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VGRAFICOS B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VHABILIDADESPESSOAIS B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VINDICACOES B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VINVESTIGACAO B WHERE B.codpessoaresp = A.CODIGO)
			   OR  exists (SELECT 0 FROM VLNTPESSOAS B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VMETAS B WHERE B.codpessoaresp = A.CODIGO)
			   OR  exists (SELECT 0 FROM VMODTURMA B WHERE B.codinstrutor = A.CODIGO)
			   OR  exists (SELECT 0 FROM VPARECERREQUISICAO B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VPARTICIPANTES B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VPCOMPL B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VPESSOAREQUISICAO B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VPESSOAREQUISITADA B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VPESSOASINSCTURMA B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VPLANEJCURSOPESSOA B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VPLANILHATURMA B WHERE B.codinstrutor = A.CODIGO)
			   OR  exists (SELECT 0 FROM VPLANORECRUTAMENTO B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VPLANOTREIN B WHERE B.codinstrutor = A.CODIGO)
			   OR  exists (SELECT 0 FROM VPPRAMEDICOES B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VPREPOSTO B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VPVV B WHERE B.codpessoaresp = A.CODIGO)
			   OR  exists (SELECT 0 FROM VPVVEVENTO B WHERE B.codpessoaresp = A.CODIGO)
			   OR  exists (SELECT 0 FROM VPVVGASTOEVENTO B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VPVVPARTICIPANTE B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VPVVPARTICIPANTEEVENTO B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VRECLAMADO B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VRECLAMANTE B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VRECRUTAMENTO B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VREPRESENTANTE B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VREQUISICAOADMISSAO B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VREQUISICAOADMISSAO B WHERE B.codrequisitante = A.CODIGO)
			   OR  exists (SELECT 0 FROM VREQUISITOPESSOAHIST B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VRESPMONBIOLOGICA B WHERE B.codigo = A.CODIGO)
			   OR  exists (SELECT 0 FROM VRESPREGAMBIENTAL B WHERE B.codigo = A.CODIGO)
			   OR  exists (SELECT 0 FROM VREUNIAOSPAT B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VRNTREGDEMANDAS B WHERE B.codpessoaverif = A.CODIGO)
			   OR  exists (SELECT 0 FROM VRNTREGDEMANDAS B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VSELECAO B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VTESTEMUNHACAT B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VTESTEMUNHACTRAB B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VTUAVCONHLACTO B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VTUAVQUALIDPESSOA B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VTURMA B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VTURMAS B WHERE B.codinstrutor = A.CODIGO)
			   OR  exists (SELECT 0 FROM VUSUARIOCURRICULO B WHERE B.codpessoa = A.CODIGO)
			   OR  exists (SELECT 0 FROM VVAGAPESSOA B WHERE B.codpessoa = A.CODIGO)
        )
        AND A.CODIGO <> INCODIGO
        AND A.NOME = INNOME
        ORDER BY CODIGO;
        
     FLAGTABELA NUMBER := 0;
     SSAIDA VARCHAR2(4000) := '';
BEGIN
   SSAIDA := 'REGISTROS ALTERADOS ( ';
   FOR RC1 IN C1 LOOP
      SSAIDA :=  SSAIDA || RC1.CODIGO || ' NAS TABELAS' || ' { ';
      SELECT COUNT (*) INTO FLAGTABELA FROM AUSOPROV B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'AUSOPROV -';
         UPDATE AUSOPROV SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM AVISITA B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'AVISITA -';
         UPDATE AVISITA SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM BEXECPROVA B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'BEXECPROVA.codpessoa -';
         UPDATE BEXECPROVA SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM BEXECPROVA B WHERE B.codavaliado = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'BEXECPROVA.codavaliado -';
         UPDATE BEXECPROVA SET codavaliado = INCODIGO WHERE codavaliado = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM BHISTORICO B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'BHISTORICO.codpessoa -';
         UPDATE BHISTORICO SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM BHISTORICO B WHERE B.codavaliado = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'BHISTORICO.codavaliado -';
         UPDATE BHISTORICO SET codavaliado = INCODIGO WHERE codavaliado = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM EALUNOS B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'EALUNOS.codpessoa -';
         UPDATE EALUNOS SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM EALUNOS B WHERE B.pai = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'EALUNOS.pai -';
         UPDATE EALUNOS SET pai = INCODIGO WHERE pai = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM EALUNOS B WHERE B.mae = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'EALUNOS.mae -';
         UPDATE EALUNOS SET mae = INCODIGO WHERE mae = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM EALUNOS B WHERE B.respacad = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'EALUNOS.respacad -';
         UPDATE EALUNOS SET respacad = INCODIGO WHERE respacad = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM EATENDIMENTO B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'EATENDIMENTO -';
         UPDATE EATENDIMENTO SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM EPROFES B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'EPROFES -';
         UPDATE EPROFES SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM HATENDENTE B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'HATENDENTE -';
         UPDATE HATENDENTE SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM HATENDIMENTOESP B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'HATENDIMENTOESP -';
         UPDATE HATENDIMENTOESP SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM KMAOOBRA B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'KMAOOBRA -';
         UPDATE KMAOOBRA SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM KREGISTROPRODUCAOQUALIDADE B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'KREGISTROPRODUCAOQUALIDADE -';
         UPDATE KREGISTROPRODUCAOQUALIDADE SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM LUSUARIO B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'LUSUARIO -';
         UPDATE LUSUARIO SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM MISMAPROP B WHERE B.codpessoaresp = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'MISMAPROP.codpessoaresp -';
         UPDATE MISMAPROP SET codpessoaresp = INCODIGO WHERE codpessoaresp = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM MISMAPROP B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'MISMAPROP.codpessoa -';
         UPDATE MISMAPROP SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM MMAOOBRAPDO B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'MMAOOBRAPDO -';
         UPDATE MMAOOBRAPDO SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM MMEDPALM B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'MMEDPALM -';
         UPDATE MMEDPALM SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM OFDESEMPENHOMENSAL B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'OFDESEMPENHOMENSAL -';
         UPDATE OFDESEMPENHOMENSAL SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM OFMAOOBRA B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'OFMAOOBRA -';
         UPDATE OFMAOOBRA SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM OFOBJINSTAL B WHERE B.idvendedor = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'OFOBJINSTAL.idvendedor -';
         UPDATE OFOBJINSTAL SET idvendedor = INCODIGO WHERE idvendedor = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM OFOBJINSTAL B WHERE B.idtecnico = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'OFOBJINSTAL.idtecnico -';
         UPDATE OFOBJINSTAL SET idtecnico = INCODIGO WHERE idtecnico = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM PANOTAC B WHERE B.codpessoaaut = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'PANOTAC.codpessoaaut -';
         UPDATE PANOTAC SET codpessoaaut = INCODIGO WHERE codpessoaaut = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM PANOTAC B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'PANOTAC.codpessoa -';
         UPDATE PANOTAC SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM PENDPESSOA B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'PENDPESSOA -';
         UPDATE PENDPESSOA SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM PEXTERNO B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'PEXTERNO -';
         UPDATE PEXTERNO SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM PFHSTEND B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'PFHSTEND -';
         UPDATE PFHSTEND SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM PFUNC B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'PFUNC -';
         UPDATE PFUNC SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM PPESSOAPT B WHERE B.codigo = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'PPESSOAPT -';
         UPDATE PPESSOAPT SET codigo = INCODIGO WHERE codigo = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM SALUNO B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'SALUNO.codpessoa -';
         UPDATE SALUNO SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM SALUNO B WHERE B.codpessoaraca = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'SALUNO.codpessoaraca -';
         UPDATE SALUNO SET codpessoaraca = INCODIGO WHERE codpessoaraca = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM SCOORDENADOR B WHERE B.codpessoavice = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'SCOORDENADOR.codpessoavice -';
         UPDATE SCOORDENADOR SET codpessoavice = INCODIGO WHERE codpessoavice = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM SCOORDENADOR B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'SCOORDENADOR.codpessoa -';
         UPDATE SCOORDENADOR SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM SDIRECAOFILIAL B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'SDIRECAOFILIAL.codpessoa -';
         UPDATE SDIRECAOFILIAL SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM SDIRECAOFILIAL B WHERE B.codpessoasec1 = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'SDIRECAOFILIAL.codpessoasec1 -';
         UPDATE SDIRECAOFILIAL SET codpessoasec1 = INCODIGO WHERE codpessoasec1 = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM SDIRECAOFILIAL B WHERE B.codpessoasec2 = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'SDIRECAOFILIAL.codpessoasec2 -';
         UPDATE SDIRECAOFILIAL SET codpessoasec2 = INCODIGO WHERE codpessoasec2 = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM SDIRETORDPTO B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'SDIRETORDPTO -';
         UPDATE SDIRETORDPTO SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM SDIRETORESCOLA B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'SDIRETORESCOLA -';
         UPDATE SDIRETORESCOLA SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM SPESSOA B WHERE B.codpessoapai = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'SPESSOA.codpessoapai -';
         UPDATE SPESSOA SET codpessoapai = INCODIGO WHERE codpessoapai = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM SPESSOA B WHERE B.codpessoamae = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'SPESSOA.codpessoamae -';
         UPDATE SPESSOA SET codpessoamae = INCODIGO WHERE codpessoamae = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM SPESSOA B WHERE B.codigo = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'SPESSOA.codigo -';
         UPDATE SPESSOA SET codigo = INCODIGO WHERE codigo = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM SPROFESSOR B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'SPROFESSOR -';
         UPDATE SPROFESSOR SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM SPSINSCRICAOAREAOFERTADA B WHERE B.codpessoaresponsavel = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'SPSINSCRICAOAREAOFERTADA -';
         UPDATE SPSINSCRICAOAREAOFERTADA SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM TVEN B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'TVEN -';
         UPDATE TVEN SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      
      SELECT COUNT (*) INTO FLAGTABELA FROM VACOESVINCULADAS B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VACOESVINCULADAS -';
         UPDATE VACOESVINCULADAS SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VADACAOAVALIADA B WHERE B.codavaliado = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VADACAOAVALIADA -';
         UPDATE VADACAOAVALIADA SET codavaliado = INCODIGO WHERE codavaliado = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VADVERTENCIA B WHERE B.codtestemun2 = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VADVERTENCIA.codtestemun2 -';
         UPDATE VADVERTENCIA SET codtestemun2 = INCODIGO WHERE codtestemun2 = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VADVERTENCIA B WHERE B.codtestemun1 = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VADVERTENCIA.codtestemun1 -';
         UPDATE VADVERTENCIA SET codtestemun1 = INCODIGO WHERE codtestemun1 = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VADVOGADO B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VADVOGADO -';
         UPDATE VADVOGADO SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VAGENDAEXAM B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VAGENDAEXAM -';
         UPDATE VAGENDAEXAM SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VAUSENCIA B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VAUSENCIA -';
         UPDATE VAUSENCIA SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VAVALIADOAD B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VAVALIADOAD -';
         UPDATE VAVALIADOAD SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VAVALIADORAD B WHERE B.codavaliador = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VAVALIADORAD -';
         UPDATE VAVALIADORAD SET codavaliador = INCODIGO WHERE codavaliador = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VBIBRIGADISTA B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VBIBRIGADISTA -';
         UPDATE VBIBRIGADISTA SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VCANDIDATOS B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         FLAGTABELA := 0;
         SELECT COUNT (*) INTO FLAGTABELA FROM VCANDIDATOS B WHERE B.codpessoa = INCODIGO;
         IF FLAGTABELA > 0 THEN
            DELETE VCANDIDATOS B WHERE B.codpessoa = RC1.CODIGO;
         ELSE
            UPDATE VCANDIDATOS SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
         END IF;
         SSAIDA := SSAIDA || 'VCANDIDATOS -';
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VCANDIDATOSCIPA B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VCANDIDATOSCIPA -';
         UPDATE VCANDIDATOSCIPA SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VCOMPETENCIAPESSOA B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VCOMPETENCIAPESSOA.codpessoa -';
         UPDATE VCOMPETENCIAPESSOA SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VCOMPETENCIAPESSOA B WHERE B.codcompetencia = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VCOMPETENCIAPESSOA.codcompetencia -';
         UPDATE VCOMPETENCIAPESSOA SET codcompetencia = INCODIGO WHERE codcompetencia = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VCOMPETENCIAPESSOAHIST B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VCOMPETENCIAPESSOAHIST -';
         UPDATE VCOMPETENCIAPESSOAHIST SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VCONSULTASPRONT B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VCONSULTASPRONT -';
         UPDATE VCONSULTASPRONT SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VCTRLVACINAL B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VCTRLVACINAL -';
         UPDATE VCTRLVACINAL SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VDESPESASREQSEL B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VDESPESASREQSEL -';
         UPDATE VDESPESASREQSEL SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VEMPRESTIMOEPI B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VEMPRESTIMOEPI -';
         UPDATE VEMPRESTIMOEPI SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VENVOLVIDOSCAT B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VENVOLVIDOSCAT -';
         UPDATE VENVOLVIDOSCAT SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VEXPPROF B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VEXPPROF -';
         UPDATE VEXPPROF SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VFUNCAOPRETENDIDA B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VFUNCAOPRETENDIDA -';
         UPDATE VFUNCAOPRETENDIDA SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VGRAFICOS B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VGRAFICOS -';
         UPDATE VGRAFICOS SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VHABILIDADESPESSOAIS B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VHABILIDADESPESSOAIS -';
         UPDATE VHABILIDADESPESSOAIS SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VINDICACOES B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VINDICACOES -';
         UPDATE VINDICACOES SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VINVESTIGACAO B WHERE B.codpessoaresp = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VINVESTIGACAO -';
         UPDATE VINVESTIGACAO SET codpessoaresp = INCODIGO WHERE codpessoaresp = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VLNTPESSOAS B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VLNTPESSOAS -';
         UPDATE VLNTPESSOAS SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VMETAS B WHERE B.codpessoaresp = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VMETAS -';
         UPDATE VMETAS SET codpessoaresp = INCODIGO WHERE codpessoaresp = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VMODTURMA B WHERE B.codinstrutor = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VMODTURMA -';
         UPDATE VMODTURMA SET codinstrutor = INCODIGO WHERE codinstrutor = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VPARECERREQUISICAO B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VPARECERREQUISICAO -';
         UPDATE VPARECERREQUISICAO SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VPARTICIPANTES B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VPARTICIPANTES -';
         UPDATE VPARTICIPANTES SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VPCOMPL B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VPCOMPL -';
         UPDATE VPCOMPL SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VPESSOAREQUISICAO B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VPESSOAREQUISICAO -';
         UPDATE VPESSOAREQUISICAO SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VPESSOAREQUISITADA B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VPESSOAREQUISITADA -';
         UPDATE VPESSOAREQUISITADA SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VPESSOASINSCTURMA B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VPESSOASINSCTURMA -';
         UPDATE VPESSOASINSCTURMA SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VPLANEJCURSOPESSOA B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VPLANEJCURSOPESSOA -';
         UPDATE VPLANEJCURSOPESSOA SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VPLANILHATURMA B WHERE B.codinstrutor = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VPLANILHATURMA -';
         UPDATE VPLANILHATURMA SET codinstrutor = INCODIGO WHERE codinstrutor = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VPLANORECRUTAMENTO B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VPLANORECRUTAMENTO -';
         UPDATE VPLANORECRUTAMENTO SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VPLANOTREIN B WHERE B.codinstrutor = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VPLANOTREIN -';
         UPDATE VPLANOTREIN SET codinstrutor = INCODIGO WHERE codinstrutor = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VPPRAMEDICOES B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VPPRAMEDICOES -';
         UPDATE VPPRAMEDICOES SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VPREPOSTO B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VPREPOSTO -';
         UPDATE VPREPOSTO SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VPVV B WHERE B.codpessoaresp = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VPVV -';
         UPDATE VPVV SET codpessoaresp = INCODIGO WHERE codpessoaresp = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VPVVEVENTO B WHERE B.codpessoaresp = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VPVVEVENTO -';
         UPDATE VPVVEVENTO SET codpessoaresp = INCODIGO WHERE codpessoaresp = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VPVVGASTOEVENTO B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VPVVGASTOEVENTO -';
         UPDATE VPVVGASTOEVENTO SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VPVVPARTICIPANTE B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VPVVPARTICIPANTE -';
         UPDATE VPVVPARTICIPANTE SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VPVVPARTICIPANTEEVENTO B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VPVVPARTICIPANTEEVENTO -';
         UPDATE VPVVPARTICIPANTEEVENTO SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VRECLAMADO B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VRECLAMADO -';
         UPDATE VRECLAMADO SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VRECLAMANTE B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VRECLAMANTE -';
         UPDATE VRECLAMANTE SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VRECRUTAMENTO B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VRECRUTAMENTO -';
         UPDATE VRECRUTAMENTO SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VREPRESENTANTE B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VREPRESENTANTE -';
         UPDATE VREPRESENTANTE SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VREQUISICAOADMISSAO B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VREQUISICAOADMISSAO.codpessoa -';
         UPDATE VREQUISICAOADMISSAO SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VREQUISICAOADMISSAO B WHERE B.codrequisitante = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VREQUISICAOADMISSAO.codrequisitante -';
         UPDATE VREQUISICAOADMISSAO SET codrequisitante = INCODIGO WHERE codrequisitante = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VREQUISITOPESSOAHIST B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VREQUISITOPESSOAHIST -';
         UPDATE VREQUISITOPESSOAHIST SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VRESPMONBIOLOGICA B WHERE B.codigo = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VRESPMONBIOLOGICA -';
         UPDATE VRESPMONBIOLOGICA SET codigo = INCODIGO WHERE codigo = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VRESPREGAMBIENTAL B WHERE B.codigo = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VRESPREGAMBIENTAL -';
         UPDATE VRESPREGAMBIENTAL SET codigo = INCODIGO WHERE codigo = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VREUNIAOSPAT B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VREUNIAOSPAT -';
         UPDATE VREUNIAOSPAT SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VRNTREGDEMANDAS B WHERE B.codpessoaverif = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VRNTREGDEMANDAS.codpessoaverif -';
         UPDATE VRNTREGDEMANDAS SET codpessoaverif = INCODIGO WHERE codpessoaverif = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VRNTREGDEMANDAS B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VRNTREGDEMANDAS.codpessoa -';
         UPDATE VRNTREGDEMANDAS SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VSELECAO B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VSELECAO -';
         UPDATE VSELECAO SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VTESTEMUNHACAT B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VTESTEMUNHACAT -';
         UPDATE VTESTEMUNHACAT SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VTESTEMUNHACTRAB B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VTESTEMUNHACTRAB -';
         UPDATE VTESTEMUNHACTRAB SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VTUAVCONHLACTO B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VTUAVCONHLACTO -';
         UPDATE VTUAVCONHLACTO SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VTUAVQUALIDPESSOA B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VTUAVQUALIDPESSOA -';
         UPDATE VTUAVQUALIDPESSOA SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VTURMA B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VTURMA -';
         UPDATE VTURMA SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VTURMAS B WHERE B.codinstrutor = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VTURMAS -';
         UPDATE VTURMAS SET codinstrutor = INCODIGO WHERE codinstrutor = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VUSUARIOCURRICULO B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VUSUARIOCURRICULO -';
         UPDATE VUSUARIOCURRICULO SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;

      SELECT COUNT (*) INTO FLAGTABELA FROM VVAGAPESSOA B WHERE B.codpessoa = RC1.CODIGO;
      IF FLAGTABELA > 0 THEN
         SSAIDA := SSAIDA || 'VVAGAPESSOA -';
         UPDATE VVAGAPESSOA SET codpessoa = INCODIGO WHERE codpessoa = RC1.CODIGO;
      END IF;
      FLAGTABELA := 0;
      SSAIDA :=  SSAIDA || '} ';
   END LOOP;
   SSAIDA := SSAIDA || ' )';
   RETURN SSAIDA;
END;
/

