/*
**  Copyright (c) 1996 by Oracle Corporation. All rights reserved. 
**    NAME
**      HelloWorld.java
**    DESCRIPTION
**      
**    RETURNS
** 
**    NOTES
**      
**    MODIFIED   (MM/DD/YY)
**     mfreedma      09/11/96 -  Added Banner
*/

class HelloWorld {
    public static void main(String args[]) {
	System.out.println("Content-type: text/html\n\n");
	System.out.println("Hello World.\n");
	System.out.println("Hello World.\n");
    }
}
